### PR TITLE
Bypass `getStaticProps`

### PR DESCRIPTION
**Pull request by ghost**
Issue: #345

DONE:
* Directly reference data from each page component's make function, rather than exporting data from `getStaticProps`

Discussion: Since we have data available to us in memory, and we are no longer reading files, the use of `getStaticProps` to gather data is superfluous. Instead, whenever we need to use data in a page component, we can directly reference the available data.

### CODE REVIEW

**Comment by ghost** [comment]
This needs too much work to catch up with master. We can resume this next week.

**Comment by tmattio** [comment]
This is great! Could you compare the bundle size @kanishka-work, I'm curious if this has an impact on it.

**Comment by ghost** [comment]
> I'm curious if this has an impact on it.

We suspect that it will hurt the bundle size, as previously mentioned, by growing the size of the data for a route in proportion to the number of languages. I don't think we will notice any difference right now.

**Comment by ghost** [comment]
After extensive thought and experiments, we like that the current implementation can handle variants and ocaml data types already, and it is able to take advantage of NextJS's full data splitting capability. We are not going to pursue this further for now. Later discussion may revisit this topic.

**Pull request closed without merging**
