### PR TITLE
Finish backfilling empty pages

### PR DESCRIPTION
**Pull request by ghost**
#124

### CODE REVIEW

**Comment by ghost** [comment]
You can see that #198 would be helpful, given the repetition here.

**Comment by ghost** [comment]
The only page that has been drafted in Tailwind Playground that isn't represented by a skeleton page is "papers archive". I don't see "papers archive" being necessary for even the first public release. It could easily be added soon after a public release, as there is already a "papers" page, which should provide the essential content.

**Comment by agarwal** [comment]
> You can see that #198 would be helpful, given the repetition here.

Okay, but I also feel that basic factoring should be done in the normal course of writing any code. Why not immediately define a component for the thin banner, which takes an argument to the Figma and Tailwind links, and reuse that everywhere. I was thinking #198 is referring to some other generalization, for which we don't yet know the right abstraction. Here it seems straightforward.

**Comment by agarwal** [comment]
> The only page that has been drafted in Tailwind Playground that isn't represented by a skeleton page is "papers archive". I don't see "papers archive" being necessary for even the first public release. It could easily be added soon after a public release, as there is already a "papers" page, which should provide the essential content.

Let's use the criteria that every possible link is active and works. So if there is a link to the "papers archive", then we want this page to exist so the link can go to it.

**Comment by ghost** [comment]
> > You can see that #198 would be helpful, given the repetition here.
> 
> Okay, but I also feel that basic factoring should be done in the normal course of writing any code. Why not immediately define a component for the thin banner, which takes an argument to the Figma and Tailwind links, and reuse that everywhere. I was thinking #198 is referring to some other generalization, for which we don't yet know the right abstraction. Here it seems straightforward.

The resusable part that I was thinking of was title and page description section.

Makes sense to create the components now. I was optimizing for getting this PR merged faster. I can create two components in this PR, but polish them further in #198 and #205

**Comment by agarwal** [comment]
Ok.

**Comment by ghost** [comment]
Merging for now and moving on to other issues. More feedback is welcome, but let's track the action items in follow-up issues so that I can get to moving content over from Tailwind Playground sooner.

**Pull request merged**
