### PR TITLE
Update nav to more closely match Bella's design

### PR DESCRIPTION
**Pull request by jonludlam**
- imported font 'Roboto Slab'
- adjusted sizes / offsets
- added more padding to the left of the text in the menu, the orange
  border seemed too close to the text on the left before
- moved the x offset to ensure they don't go off the screen
- Fixed SVG rendering on Safari

### CODE REVIEW

**Review by ghost — APPROVED** [review]
I inspected briefly at two screen sizes. I did not review the CSS in detail.

**Comment by ghost** [comment]
> Fixed SVG rendering on Safari

I can't find this in the diff. I just wanted to check that you didn't miss committing a local file?

**Comment by jonludlam** [comment]
> > Fixed SVG rendering on Safari
> 
> I can't find this in the diff. I just wanted to check that you didn't miss committing a local file?

It was embedding the SVG in a div with explicit width/height that did it, so the fix is within the html.

**Comment by jonludlam** [comment]
> > > Fixed SVG rendering on Safari
> > 
> > 
> > I can't find this in the diff. I just wanted to check that you didn't miss committing a local file?
> 
> It was embedding the SVG in a div with explicit width/height that did it, so the fix is within the html.

In fact it was probably the removal of one of these: `absolute flex items-center justify-center`

**Comment by avsm** [comment]
Confirmed icons are fixed on Safari and iPad as well!

**Pull request merged**
