### PR TITLE
Continuation of PR #466

### PR DESCRIPTION
**Pull request by shreyaswikriti**
Fixed issue #415 
Applies LogoCloud.res and Page.res module with some minor changes.
Screenshot from 2021-07-19 03-53-39
Screenshot from 2021-07-19 03-54-05
Screenshot from 2021-07-19 03-54-35
Screenshot from 2021-07-19 03-54-45
## Modified relative paths:

https://v3-ocaml-org-git-BRANCH_NAME-ocaml.vercel.app/PATH/TO/PAGE

## Contributor Pre-flight Checklist

- [ ] Accessibility check - checked pa11y report for modified pages, observing new errors
- [ ] Responsive check - visually inspected vercel preview, using responsive tool to toggle between desktop and mobile view
- [ ] HTML review - use browser DOM/Page inspector to inspect generated HTML within `<div id="__next>"` element

### CODE REVIEW

**Comment by patricoferris** [comment]
This is great, thanks @shreyaswikriti ! One thing I noticed after a quick glance at the code is that page is still using the hard-coded list of companies and not the one that should be available from ood (see https://github.com/ocaml/ood/tree/main/data/industrial_users/en). Is there a reason for this or could we make the switch now to use the real list ?

**Comment by shreyaswikriti** [comment]
Thanks for reviewing. I didn't know we have data available in ood. I'll modify this PR with ood data right away.

**Comment by shreyaswikriti** [comment]
I have added the ood data to this page.
Screenshot from 2021-07-20 10-15-44

Btw there is one image file in public/users i.e, forallsecure.svg . It's in an incorrect extension.(is in HTML version needs to be corrected in ood data)

**Comment by patricoferris** [comment]
This looks great and I'm happy to merge now, I've created the follow-up for fixing the image in ood https://github.com/ocaml/ood/issues/54 -- similarly to academic institutions, I think the next step is probably to define a standalone page per entry to display the information about the company? 

@kanishka-work are you happy enough with some of the changes made to the core components like `Page` and `LogoCloud` ?

**Comment by ghost** [comment]
> are you happy enough with some of the changes made to the core components like Page and LogoCloud ?

I'm happy with it. I will note a few optional changes, if you are inspired to do them now or in a follow-up issue:

* Consider keeping the constrained width container for the title:
image
* Consider moving the padding from the `a` tag to the `div` within, for the logocloud item

**Review by ghost — APPROVED** [review]

**Comment by patricoferris** [comment]
In the spirit of keeping things moving I've merged, @shreyaswikriti feel free to create follow-up issues (and PRs) for the remaining comments if you want :))

**Pull request merged**
