### PR TITLE
Integrate subset of docs

### PR DESCRIPTION
**Pull request by jonludlam**
Slightly annoyingly, it seems that you have to explicitly ask for `index.html` here: that is, you can't just go to `https://v3.ocaml.org/packages/` - you have to go to `https://v3.ocaml.org/packages/index.html`.

### CODE REVIEW

**Comment by jonludlam** [comment]
It's a bit noisy!

**Comment by ghost** [comment]
@tmattio or @patricoferris Please ensure master is compiling soon so that this PR can be merged. Thanks!

**Comment by tmattio** [comment]
@kanishka-work I reverted the last merge in `ood`, so this should be ok now (c.f. slack)

**Comment by ghost** [comment]
> Slightly annoyingly, it seems that you have to explicitly ask for index.html here

I haven't looked into all the NextJS settings related to this. We might find a setting that helps.

**Comment by ghost** [comment]
I suggest keeping this PR open and continuing to deliberate on our preferred method of integration, but let's start by using the nextjs redirect functionality (https://nextjs.org/blog/incremental-adoption#rewrites) to redirect /packages to an externally deployed instance of the docs site in a separate PR and merge that first?

**Comment by ghost** [comment]
@jonludlam I believe I understand all the issues that we have encountered. I am polishing up a PR with appropriate changes and workarounds. Once that PR is merged, I will test out this branch locally and on Vercel and confirm that the changes have addressed all observed issues.

**Comment by ghost** [comment]
I incorporated the changes in master which should address a few issues that this branch was encountering.

**Comment by ghost** [comment]
@jonludlam I tested out this branch locally with the latest changes. If I hack the links to the CSS files such as `<link rel="stylesheet" href="tailwind.css" />` to use absolute paths, then the pages render as expected. Overall, we might need to reason about when and how to invoke webpack to accomplish cache busting (https://webpack.js.org/guides/caching/) in a little while.

After the relative path issues are resolved, we can keep testing out the local development and Vercel builds to ensure repeated invocations of `link_docs.sh` do not encounter any errors.

**Comment by jonludlam** [comment]
OK, having thought some more about this - and in particular about the observation that this makes the build noticably longer, I think we're pushing in the wrong direction.

The docs pipeline is producing gigs and gigs of data, and even the small subset we're pulling in in this PR is annoyingly slow. However, the amount of data this site is currently producing is quite small, comparatively. I think therefore it might make more sense for the build of this site to push to the git repo housing the docs rather than doing it the other way around as we are here.

So I propose to close this PR and instead figure out a way to push the build output the other way.

**Comment by ghost** [comment]
> therefore it might make more sense for the build of this site to push to the git repo housing the docs rather than doing it the other way around as we are here.

This sounds like it could scale better. It may take some thought to properly merge outputs.

I also see potential in using two servers and having this site use rewrites to transparently forward requests for the `/packages` subpath, as NextJS suggests (https://nextjs.org/blog/incremental-adoption#rewrites).

My most recent PR removed one step that was only functioning as a validation (`next export`) which was also proportional to the number of files in `/public`. After that was removed, this branch is five seconds slower than a regular build. I assume this branch includes one package, so five seconds per package would still be very slow.

**Pull request closed without merging**
