### PR TITLE
Consolidate Lib Directories

### PR DESCRIPTION
**Pull request by rdavison**
Issue: https://github.com/ocaml/v3.ocaml.org/issues/141

I consolidated the four directories `bindings`, `common`, `components`, and `layouts` into the `lib` directory.  I also updated the `tailwind.config`, `gitignore`, `bsconfig`, and `pages/_app.js` files to account for the consolidation.

### CODE REVIEW

**Comment by ghost** [comment]
> I consolidated the four directories bindings, common, components, and layouts into the lib directory.

I would use `src` similar to rescript-lang.org and tailwindcss.com implementation. I see two potential advantages of using src:

* there is no overlap between bucklescript compiler internal directories and source directories
* you can possibly also move `pages` to `src/pages`, because of this option in nextjs: https://nextjs.org/docs/advanced-features/src-directory

Overall, I don't care too strongly one way or another, but @agarwal had some strong opinions on this topic generally.

**Comment by agarwal** [comment]
We discussed and decided:
- `src/` is where all library modules go.
- `pages/` stays at the root level. That's better to avoid extra hierarchy and since it is NextJS's default.

**Review by ghost — APPROVED** [review]
I looked through changes and also scanned through the files for any additional references to directory names. This PR looks ready to merge, once latest feedback has been incorporated.

As a sanity check, run `npx yarn build` and check the exit code of that command. Also, start the test server quickly and browse a few pages as a quick sanity check.

**Comment by rdavison** [comment]
I moved lib to src in https://github.com/ocaml/v3.ocaml.org/pull/346/commits/7e59f835da8af1f9fae732e3cdf247c7582818fc

**Comment by rdavison** [comment]
> As a sanity check, run npx yarn build and check the exit code of that command. Also, start the test server quickly and browse a few pages as a quick sanity check.

Ran the sanity checks. Everything looks good to me.

**Pull request merged**
